### ISSUE TITLE
selectize not work

### ISSUE THREAD

**Issue by donhuvy** [servicechannel/selectize#2]
1. source code: https://github.com/donhuvy/selectizeExamples
2. Run file performance.html
3. Error
![t1](https://cloud.githubusercontent.com/assets/1328316/18155089/3bd2d03a-7034-11e6-973d-2d2186c591d7.PNG)

please help me an example what use lazy loading/lazy selectize.

**Comment by azinevich** [comment]
There was a typo in examples, please correct lazyselectize -> lazySelectize, it should work

**Comment by donhuvy** [comment]
Thank friend!
